### ISSUE TITLE
Re-review

### ISSUE THREAD

**Issue by vr8hub** [Gragt/charles-kingsley_the-water-babies#2]
Just a few minor things.

- [x] The `<div>` used for the former tables looks great, except for the page break before/after CSS. I'm not sure why that's there? It is, of course, causing page breaks before and after those lists, which aren't in the scans. I didn't think we want the avoid, either, but when I built the book I saw that it split half of a line on one page and half on the next. What's up with that? Anyway, looks like the avoid is needed. :)
- [x] Re the ch. 4 lists, I wonder (I know, be afraid)… the "sub-lists" in the first two items are (to me) clearly sub-lists, and should be ul's, as you have them. But looking afresh at 3-5, I wonder if those should just be multiple `<p>`s in a single `<li>`? It makes it simpler in structure, and eliminates all of the `ol` CSS. A `li p` selector has to be added to the existing `li p:first-child`, but that's it. And maybe it better represents the data: the "list of things" in 3-5 are not a _sub_-list, but just a list of things which can be naturally expressed with multiple `<p>`s. That seems clearer to me on the surface, but I can be talked out of it. :)
- [x] The replacing the ellipsis with a 3-em dash is editorial since the text is being modified. Sorry, I assumed, but should have said that explicitly. Changing the message requires a rebase, but it's the easiest kind of rebase. If you haven't done it before, let me know and I'll give you the steps.
- [x] Ditto the changing of the case of that _really_ long title.
- [x] Again, I should have said explicitly; we don't italicize non-epic poems, but we do quote them (SEMoS 8.2.11.3), so Ode to Duty should have quotes.
- [x] For the dedication, using a `span` is not wrong, but we have a lot of precedent in the corpus to use `b` in that situation.
- [x] Also, from the scans it appears we want the line-height on the last paragraph as well, so I think the following makes things a little simpler? We format everything using a plain `p`, then just override what we need to for the last paragraph. (We don't _need_ the `margin-bottom: 0` in this particular case (there's nothing after it), but just for completeness…)
````
section[epub|type~="dedication"] p{
	font-variant: small-caps;
	line-height: 2;
	margin-bottom: 2.5em;
	text-indent: 0;
}

section[epub|type~="dedication"] p:last-of-type{
	font-size: .75em;
	margin-bottom: 0;
}

section[epub|type~="dedication"] b{
	font-size: 1.25em;
}
````

**Comment by Gragt** [comment]
Sorry: I’m swamped again. This shouldn’t take too long but I’ve got other (far less fun and important) things to do. I should hopefully be able to wrap it up by the end of week.

Well, okay, I’ll just comment on the first item. :) The idea behind the breaks before and after is that without them the columns would sometimes be cut in the middle instead of being displayed as a whole on a single screen. Of course, that creates its own problems, as you saw. I guess I’ll just drop them since they create more problems—if you have an elegant solution for this, feel free to share it! And yes, I ran into many problems without the `avoid`.

**Comment by Gragt** [comment]
Alright, all done! All in all not very big changes but exam period always takes most of my attention away.

* I don’t blame you for not mentioning the obvious. I should’ve know those things but they simply escaped me—I’m grateful you caught them! (Since a rebase was necessary, I added the quote to the poem by editing the corresponding commit: it was a minor change that corrected an oversight.)
* That lead me to realise that one of the early commits with manual typography changes mixed editorial and non-editorial changes. I split that one into two commits—same message for both but one is tagged with [Editorial]. (I had the same problem in my previous production; the rule is very clear in my head but I somehow end up mixing editorial and non-editorial.)
* Thanks for the dedication CSS. I was already thinking about it but you saved me the trouble.
* The chapter 4 list does look a lot better now while being visually identical as before, and the CSS is much simpler. I only wonder whether it is okay to have items 3–5 mix `<ol>` and `<ul>` at the top level—isn’t it technically the same ordered list but interrupted by commentary? Of course, having everything as `<ol>` would mean re-adding CSS to remove the list styling—which would be annoying but not impossible. (No, I don’t insist that you have me make more changes on this; I’m just wondering.)

With all that said, barring some gross error on my part (the chapter 4 list?), that should hopefully be it.
